services:
  db:
    image: postgres:16
    container_name: droppy-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: droppy
      POSTGRES_USER: droppy
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
      # ← монтируем папку, где реально лежат 01_schema.sql и 02_seed.sql
      - ./src/main/java/resources/db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U droppy -d droppy"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
